import { useState, useRef } from 'react';
import { X, Bookmark, Download, FileText, Printer } from 'lucide-react';
import { RichContent } from './ChatInterface.jsx';

const fmtDate = (ts) => new Intl.DateTimeFormat('en-US', {
  month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit',
}).format(new Date(ts || Date.now()));

export const ReportPanel = ({ content, title, onClose, onSave, folders = [] }) => {
  const [saveMenuOpen, setSaveMenuOpen] = useState(false);
  const contentRef = useRef(null);
  const saveRef = useRef(null);

  const handlePrint = () => {
    const w = window.open('', '_blank', 'width=900,height=700');
    const stylesheet = document.querySelector('link[rel=stylesheet]')?.href || '';
    w.document.write(`<html><head><title>${title || 'Report'}</title>${stylesheet ? `<link rel="stylesheet" href="${stylesheet}">` : ''}<style>body{padding:32px;background:#fff;font-family:system-ui,-apple-system,sans-serif}@media print{body{padding:16px}}</style></head><body>${contentRef.current?.innerHTML || ''}</body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 600);
  };

  const folderList = folders.length > 0 ? folders : [
    { id: 'reports', name: 'Reports' },
    { id: 'strategies', name: 'Strategies' },
  ];

  return (
    <div className="w-[55%] min-w-[420px] border-l border-slate-200 bg-white flex flex-col h-screen">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 shrink-0">
        <div className="flex items-center gap-3 min-w-0">
          <img src="/meta-icon.svg" alt="Meta" className="w-8 h-8 shrink-0" />
          <div className="min-w-0">
            <p className="text-lg font-bold text-slate-900 truncate">{title || 'Report'}</p>
            <p className="text-xs text-slate-400">Generated by AI Ad Manager · {fmtDate()}</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 shrink-0">
          {/* Save to folder */}
          <div className="relative" ref={saveRef}>
            <button onClick={() => setSaveMenuOpen(!saveMenuOpen)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-blue-600 hover:bg-blue-50 border border-blue-200 transition-colors">
              <Bookmark size={13} /> Save
            </button>
            {saveMenuOpen && (
              <div className="absolute right-0 top-full mt-1 bg-white border border-slate-200 rounded-lg shadow-lg z-20 py-1 w-48">
                <p className="px-3 py-1.5 text-[10px] font-semibold text-slate-400 uppercase tracking-wider">Save to folder</p>
                {folderList.map(folder => (
                  <button key={folder.id}
                    onClick={() => { onSave?.(folder.id); setSaveMenuOpen(false); }}
                    className="w-full flex items-center gap-2 px-3 py-2 text-xs font-medium text-slate-700 hover:bg-blue-50 hover:text-blue-600 transition-colors">
                    <FileText size={13} className="text-blue-400" />
                    {folder.name}
                  </button>
                ))}
              </div>
            )}
          </div>
          {/* Print / Download */}
          <button onClick={handlePrint}
            className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
            title="Print report">
            <Printer size={16} />
          </button>
          {/* Close */}
          <button onClick={onClose}
            className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
            title="Close panel">
            <X size={18} />
          </button>
        </div>
      </div>

      {/* Report content */}
      <div className="flex-1 overflow-y-auto">
        <div ref={contentRef} className="max-w-3xl mx-auto px-8 py-8">
          {/* Report header */}
          <div className="flex items-center gap-4 mb-8 pb-6 border-b border-slate-200">
            <img src="/meta-icon.svg" alt="Meta" className="w-12 h-12 opacity-80" />
            <div>
              <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">{title || 'Report'}</h1>
              <p className="text-sm text-slate-400 mt-1">AI Ad Manager · Meta Ads Analysis</p>
            </div>
          </div>

          {/* Rendered content using same rich card pipeline */}
          <div className="text-sm leading-relaxed text-slate-700">
            <RichContent text={content} />
          </div>
        </div>
      </div>
    </div>
  );
};
